### ISSUE TITLE
can't launch shadow

### ISSUE THREAD

**Issue by distrair** [imgk/shadow#44]
After compiling and adding config file, it shows an error:
```
PS C:\Users\<username>\go\bin> .\shadow.exe -v
2022/04/19 17:45:01 json: cannot unmarshal string into Go struct field Conf.name_server of type []string
panic: json: cannot unmarshal string into Go struct field Conf.name_server of type []string

goroutine 1 [running]:
log.Panic({0xc000117ef0, 0xb, 0xc0002823b0})
        log/log.go:354 +0x65
main.main()
        github.com/imgk/shadow@v0.0.0-20220128031617-9ea50f40f661/main.go:61 +0x22c
```
How to fix it?

**Comment by distrair** [comment]
Update: probably problem is in "server_name" string in config.json file.
But i still don't know how to fix this problem.

**Comment by imgk** [comment]
`"name_server": ["https://1.1.1.1:443/dns-query"]`

**Comment by distrair** [comment]
Thanks, it worked!
